// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4RRDgsEdPtPQxA5R8Zbj_Rbnc3EbXPnA',
    appId: '1:932590861487:android:ccba14c5b4b6f04fc8e85a',
    messagingSenderId: '932590861487',
    projectId: 'aiproject-c4d80',
    databaseURL: 'https://aiproject-c4d80-default-rtdb.firebaseio.com',
    storageBucket: 'aiproject-c4d80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfyyyObvQxuUFVaeLbmLT64dWDvClC79s',
    appId: '1:932590861487:ios:757e041cbcbfb5c0c8e85a',
    messagingSenderId: '932590861487',
    projectId: 'aiproject-c4d80',
    databaseURL: 'https://aiproject-c4d80-default-rtdb.firebaseio.com',
    storageBucket: 'aiproject-c4d80.appspot.com',
    iosBundleId: 'com.example.foreignlanguage',
  );
}
